# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"

  lane :beta do
    pilot( api_key_path: "fastlane/27H4MK7PP6.json" )
    get_certificates
    get_provisioning_profile
    increment_build_number(
        build_number: latest_testflight_build_number + 1
    )
    build_app(
	    configuration: "Debug"
    )
    upload_to_testflight(
	    skip_waiting_for_build_processing: true,
    )
    slack(
        message: "Testflight 배포에 성공했습니다!",
        slack_url: "https://hooks.slack.com/services/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",
    )
  end
  error do |lane, exception, options|
    slack(
      message: "에러 발생 : #{exception}",
      success: false,
      slack_url: "https://hooks.slack.com/services/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",
    )
  end
end
