default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"

  lane :beta do
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT']
    )

    match(
      git_url: "git@github.com:My-Pack/FastlaneMatch.git",
      storage_mode: "git",
      type: "appstore",
      readonly: true,
      keychain_name: ENV['KEYCHAIN_NAME'],
      clone_branch_directly: true
    )

    increment_build_number(
        build_number: latest_testflight_build_number + 1
    )

    gym(
      clean: true,
      export_options: {
        method: "app-store",
        signingStyle: "manual"
      },
      export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight
    slack(
        message: "Testflight 배포에 성공했습니다!",
        slack_url: ENV['SLACK_URL']
    )
  end
  error do |lane, exception, options|
    slack(
      message: "에러 발생 : #{exception}",
      success: false,
      slack_url: ENV['SLACK_URL']
    )
  end
end
