name: build verification

on:
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Check out branch
      uses: actions/checkout@v2

    - name: Lint Check
      run: swiftlint .

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
