name: build verification

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Check out branch
      uses: actions/checkout@v2

    - name: Lint Check
      run: swiftlint .

    - name: Xcode Project Build
      run: xcodebuild clean test -project MyPack.xcodeproj -scheme MyPack -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest'

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload-file-path: "./payload-slack-content.json"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
