name: build verification

on:
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Check out branch
      uses: actions/checkout@v2

    - name: Lint Check
      run: swiftlint .

    - name: Xcode Project Build
      run: xcodebuild clean test -project MyPack.xcodeproj -scheme MyPack -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest'

    - name: Run tests
      run: swift test -v
