name: dev build and deploy

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - run: bundle lock --add-platform x86_64-darwin-19
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - uses: maierj/fastlane-action@v3.0.0
      with:
        lane: 'beta'
